Match User rack
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitEmptyPasswords no
    AuthenticationMethods publickey
    AuthorizedKeysCommand /usr/bin/python3 /opt/testing-rack/keys.py %t %k
    AuthorizedKeysCommandUser testing-rack
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
    PermitTTY yes
    ForceCommand /usr/bin/python3 /opt/testing-rack/gateway.py
