[Service]
ExecStart=
ExecStart=/bin/bash -c "source /etc/profile; if test -r /data/rack-display/launch.py; then exec /usr/local/venv/bin/python -u /data/rack-display/launch.py; else exec /usr/local/venv/bin/python -u /usr/comma/magic.py; fi"
Restart=on-failure
RestartSec=5
